hidden_inventory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    
    path('create-ajax/', create_item_ajax, name='create_item_ajax'), 
    path('edit-ajax/<int:id>', edit_item_ajax, name='edit_item_ajax'),
    path('add-ajax/<int:id>', increment_item_ajax, name='increment_item_ajax'),
    path('reduce-ajax/<int:id>/', decrement_item_ajax, name='decrement_item_ajax'),
    path('delete-ajax/<int:id>/', delete_item_ajax, name='delete_item_ajax'), 

    path('create-flutter/', create_item_flutter, name='create_item_flutter'),

    path('create-item/', create_item, name='create_item'),
    path('edit-item/<int:id>', edit_item, name='edit_item'),
    path('add/<int:id>/', increment_item, name='increment_item'),
    path('reduce/<int:id>/', decrement_item, name='decrement_item'),
    path('delete/<int:id>/', delete_item, name='delete_item'),
    
    path('get-items/', get_items_json, name='get_items_json'),
    path('get-item/<int:id>', get_an_item, name='get_an_item'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
]

main/models.py
from django.contrib.auth.models import User
from django.db import models

class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    amount = models.IntegerField(default=1)
    description = models.TextField()
    price = models.IntegerField()
    tags = models.CharField(max_length=40, default="")
    date_added = models.DateField(auto_now_add=True)

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "description", "price", "tags"]

main/views.py
import datetime
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound, JsonResponse
from django.core import serializers
from main.forms import ItemForm
from django.urls import reverse
from main.models import Item
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages  
from django.contrib.auth.decorators import login_required
import json

# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    if 'last_login' not in request.COOKIES.keys():
        return redirect('main:login')
    
    items = Item.objects.filter(user=request.user)

    context = {
        'display_name': request.user.username,
        'subject_class': 'PBP A',
        'app_name': 'Hidden Inventory',
        'items': items,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def get_items_json(request):
    items = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', items))

def get_an_item(request, id):
    item = Item.objects.filter(user=request.user, pk=id)
    return HttpResponse(serializers.serialize('json', item))

## User Accounts
def register(request):
    if 'last_login' in request.COOKIES.keys():
            return redirect('main:login')
    
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:show_main')
    context = {'form':form, 'page_title': "Register"}
    return render(request, 'register.html', context)

def login_user(request):
    if 'last_login' in request.COOKIES.keys():
            return redirect('main:show_main')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Incorrect username or password')
    context = {'page_title': "Login"}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

# Item related
@login_required(login_url='/login')
def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form, 'page_title': "Register Item", 'display_name': request.user.username, 'subject_class': 'PBP A', 'last_login': request.COOKIES['last_login']}
    return render(request, "create_item.html", context)

@login_required(login_url='/login')
def create_item_ajax(request):
    if request.method == 'POST':
        item = Item()
        item.name = request.POST.get("name")
        item.amount = request.POST.get("amount")
        item.price = request.POST.get("price")
        item.description = request.POST.get("description")
        item.tags = request.POST.get("tags")
        item.user = request.user
        item.save()

        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

@login_required(login_url='/login')
def edit_item(request, id):
    # Get product berdasarkan ID
    item = Item.objects.get(pk = id)

    # Set product sebagai instance dari form
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_item.html", context)

@login_required(login_url='/login')
def edit_item_ajax(request, id):
    item = Item.objects.get(id=id)
    if request.method == 'POST' and request.user == item.user:
        item.name = request.POST.get("name")
        item.amount = request.POST.get("amount")
        item.price = request.POST.get("price")
        item.description = request.POST.get("description")
        item.tags = request.POST.get("tags")
        item.save()

        return HttpResponse(b"EDITED", status=201)
    return HttpResponseNotFound()

@login_required(login_url='/login')
def increment_item(request, id):
    item = Item.objects.get(id=id)
    item.amount += 1
    item.save()
    return HttpResponseRedirect(reverse('main:show_main'))

@login_required(login_url='/login')
@csrf_exempt
def increment_item_ajax(request, id):
    item = Item.objects.get(id=id)
    if request.method == 'POST' and request.user == item.user:
        item.amount += 1
        item.save()

        return HttpResponse(b"ADDED", status=201)
    return HttpResponseNotFound()

@login_required(login_url='/login')
def decrement_item(request, id):
    item = Item.objects.get(id=id)
    item.amount -= 1
    if item.amount <= 0:
        item.delete()
    else:
        item.save()
    return HttpResponseRedirect(reverse('main:show_main'))

@login_required(login_url='/login')
@csrf_exempt
def decrement_item_ajax(request, id):
    item = Item.objects.get(id=id)
    if request.method == 'POST' and request.user == item.user:
        item.amount -= 1
        if (item.amount < 0):
            item.amount = 0
        item.save()

        return HttpResponse(b"REDUCED", status=201)
    return HttpResponseNotFound()

@login_required(login_url='/login')
def delete_item(request, id):
    item = Item.objects.get(id=id)
    if request.user == item.user:
        item.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

@login_required(login_url='/login')
def delete_item_ajax(request, id):
    item = Item.objects.get(id=id)
    if request.method == 'POST' and request.user == item.user:
        item.delete()
        return HttpResponse(b"DELETED", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def create_item_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_item = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            price = int(data["price"]),
            tags = data["tags"],
            description = data["description"]
        )

        new_item.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

# Data related
def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

## 404
def custom_404(request, exception):
    return render(request, '404.html', status=404, context={'page_title': 'Uh oh'})

main/templates/ajax_add_modal.html
<div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="add-modal-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-light-subtle">
                <h1 class="modal-title fs-5" id="add-modal-label">Add New Item</h1>
            </div>
            <div class="modal-body">
                <form id="add-item-form" class="needs-validation" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="form-floating mb-2">
                        <input type="text" class="form-control bg-body-tertiary" id="add-item-name" name="name"></input>
                        <label for="add-item-name">Name</label>
                        <div class="invalid-feedback">Please set the item name</div>
                    </div>

                    <div class="row g-2 mb-2">
                        <div class="col-md">
                            <div class="form-floating">
                                <input type="number" class="form-control bg-body-tertiary" id="add-item-amount" min="0" step="1" name="amount"></input>
                                <label for="add-item-amount">Amount</label>
                                <div class="invalid-feedback">Please set a positive amount</div>
                            </div>        
                        </div>
                        <div class="col-md">
                            <div class="form-floating">
                                <input type="number" class="form-control bg-body-tertiary" id="add-item-price" min="1" step="1" name="price"></input>
                                <label for="add-item-price">Price</label>
                                <div class="invalid-feedback">Please set a price</div>
                            </div> 
                        </div>
                    </div>
                      
                    <div class="form-floating mb-2">
                        <textarea class="form-control bg-body-tertiary" id="description" id="add-item-description" style="height: 100px" name="description"></textarea>
                        <label for="add-item-description">Description</label>
                    </div>                 
                    <div class="form-floating">
                        <input type="text" class="form-control bg-body-tertiary" id="add-item-tags" name="tags"></input>
                        <label for="add-item-tags">Tags</label>
                        <div class="invalid-feedback">Please set at least one tag</div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">
                    <span>
                        <svg class="bi me-1 p-0" width="18" height="18" fill="currentColor" viewBox="2 2 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12 2c5.523 0 10 4.477 10 10s-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2Zm0 1.5a8.5 8.5 0 1 0 0 17 8.5 8.5 0 0 0 0-17ZM12 7a.75.75 0 0 1 .75.75v3.5h3.5a.75.75 0 0 1 0 1.5h-3.5v3.5a.75.75 0 0 1-1.5 0v-3.5h-3.5a.75.75 0 0 1 0-1.5h3.5v-3.5A.75.75 0 0 1 12 7Z"/></svg>
                    </span>
                    Add Item
                </button>
            </div>
        </div>
    </div>
</div>

main/templates/ajax_delete_modal.html
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="delete-modal-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-light-subtle">
                <h1 class="modal-title fs-5" id="delete-modal-label">Delete Item Confirmation</h1>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete <strong id="deleteConfirmationText" class="text-danger">this item</strong>?</p>
                <form id="delete-item-form" onsubmit="return false;">{% csrf_token %}</form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger ps-2" id="button_delete" data-bs-dismiss="modal">
                    <span>
                        <svg class="me-1 mb-1" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" id="theme-icon" viewBox="0 0 16 16">
                            <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                        </svg>
                    </span>
                    Delete
                </button>
                <button type="button" class="btn btn-outline-primary" data-bs-dismiss="modal">Nevermind</button>
            </div>
        </div>
    </div>
</div>

main/templates/ajax_edit_modal.html
<div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="edit-modal-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-light-subtle">
                <h1 class="modal-title fs-5" id="edit-modal-label">Edit Item</h1>
            </div>
            <div class="modal-body">
                <form id="edit-item-form" class="needs-validation" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="form-floating mb-2">
                        <input type="text" class="form-control bg-body-tertiary" id="edit-item-name" name="name" value=""></input>
                        <label for="edit-item-name">Name</label>
                        <div class="invalid-feedback">Please set the item name</div>
                    </div>

                    <div class="row g-2 mb-2">
                        <div class="col-md">
                            <div class="form-floating">
                                <input type="number" class="form-control bg-body-tertiary" id="edit-item-amount" min="0" step="1" name="amount" value=""></input>
                                <label for="edit-item-amount">Amount</label>
                                <div class="invalid-feedback">Please set a positive amount</div>
                            </div>        
                        </div>
                        <div class="col-md">
                            <div class="form-floating">
                                <input type="number" class="form-control bg-body-tertiary" id="edit-item-price" min="1" step="1" name="price" value=""></input>
                                <label for="edit-item-price">Price</label>
                                <div class="invalid-feedback">Please set a price</div>
                            </div> 
                        </div>
                    </div>
                      
                    <div class="form-floating mb-2">
                        <textarea class="form-control bg-body-tertiary" id="description" id="edit-item-description" style="height: 100px" name="description" value=""></textarea>
                        <label for="edit-item-description">Description</label>
                    </div>                 
                    <div class="form-floating">
                        <input type="text" class="form-control bg-body-tertiary" id="edit-item-tags" name="tags" value=""></input>
                        <label for="edit-item-tags">Tags</label>
                        <div class="invalid-feedback">Please set at least one tag</div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">Discard</button>
                <button type="submit" class="btn btn-primary" id="button_edit" data-bs-dismiss="modal">
                    <span>
                        <svg class="me-1 p-0" width="18" height="18" fill="currentColor" viewBox="2 2 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M5.75 3A2.75 2.75 0 0 0 3 5.75v12.5A2.75 2.75 0 0 0 5.75 21h4.249a2.112 2.112 0 0 1 .062-.593l.227-.907H7.5v-5.25a.75.75 0 0 1 .75-.75h6.603l1.435-1.435A2.258 2.258 0 0 0 15.75 12h-7.5A2.25 2.25 0 0 0 6 14.25v5.25h-.25c-.69 0-1.25-.56-1.25-1.25V5.75c0-.69.56-1.25 1.25-1.25H7v2.75A2.25 2.25 0 0 0 9.25 9.5h4.5A2.25 2.25 0 0 0 16 7.25V4.523c.358.06.692.23.952.49l2.035 2.035c.329.328.513.773.513 1.238v1.721c.07-.005.142-.007.213-.007h.002c.437 0 .875.087 1.285.261V8.287a3.25 3.25 0 0 0-.952-2.299l-2.035-2.035A3.25 3.25 0 0 0 15.714 3H5.75ZM8.5 7.25V4.5h6v2.75a.75.75 0 0 1-.75.75h-4.5a.75.75 0 0 1-.75-.75Z"/><path d="M19.715 11h-.002c-.585 0-1.17.223-1.615.67l-5.902 5.902a2.684 2.684 0 0 0-.707 1.247l-.458 1.831a1.087 1.087 0 0 0 1.319 1.318l1.83-.457a2.684 2.684 0 0 0 1.248-.707l5.902-5.902A2.285 2.285 0 0 0 19.715 11Z"/></svg>
                    </span>
                   Save edits
                </button>
            </div>
        </div>
    </div>
</div>

main/templates/create_item.html
{% extends 'base.html' %} 

{% block content %}
<h1>Register New Item</h1>

<div class="container-fluid col-lg-6 col-md-8 col-sm-12 create-table rounded border p-4 pb-1 shadow-sm overflow-scroll">
    <form method="POST">
        {% csrf_token %}
        <table class="table table-borderless">
            <tbody>
                {{ form.as_table }}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="2" style="text-align: right;">
                        <button type="submit" class="btn btn-primary">Register item</button>
                        <a href="{% url 'main:show_main' %}">
                            <button type="button" class="btn btn-outline-danger">Cancel</button>
                        </a>
                    </td>
                </tr>
            </tfoot>
        </table>
    </form>
</div>

{% endblock %}

main/templates/edit_item.html
{% extends 'base.html' %} 

{% block content %}
<h1>Edit Item</h1>

<div class="container-fluid col-lg-6 col-md-8 col-sm-12 create-table rounded bg-light bg-gradient border p-4 pb-1 shadow-sm overflow-scroll">
    <form method="POST">
        {% csrf_token %}
        <table class="table table-borderless">
            <tbody>
                {{ form.as_table }}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="2" style="text-align: right;">
                        <button type="submit" class="btn btn-primary">
                            <span class="me-1 align-top">
                                <svg width="20" height="20" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M6.75 3h-1A2.75 2.75 0 0 0 3 5.75v12.5A2.75 2.75 0 0 0 5.75 21H6v-6a2.25 2.25 0 0 1 2.25-2.25h7.353l1.788-1.788A3.28 3.28 0 0 1 19.713 10h.002c.437 0 .875.087 1.285.261V8.287a3.25 3.25 0 0 0-.952-2.299l-2.035-2.035A3.25 3.25 0 0 0 15.75 3v4.5a2.25 2.25 0 0 1-2.25 2.25H9A2.25 2.25 0 0 1 6.75 7.5V3Z"/><path d="m14.103 14.25-2.615 2.615a3.685 3.685 0 0 0-.969 1.712l-.458 1.83c-.05.202-.07.4-.062.593H7.5v-6a.75.75 0 0 1 .75-.75h5.853ZM14.25 3v4.5a.75.75 0 0 1-.75.75H9a.75.75 0 0 1-.75-.75V3h6Z"/><path d="M19.715 11h-.002c-.585 0-1.17.223-1.615.67l-5.902 5.902a2.684 2.684 0 0 0-.707 1.247l-.458 1.831a1.087 1.087 0 0 0 1.319 1.318l1.83-.457a2.684 2.684 0 0 0 1.248-.707l5.902-5.902A2.285 2.285 0 0 0 19.715 11Z"/></svg>
                            </span>
                            Save edits
                        </button>
                        <a href="{% url 'main:show_main' %}">
                            <button type="button" class="btn btn-outline-danger">Discard</button>
                        </a>
                    </td>
                </tr>
            </tfoot>
        </table>
    </form>
</div>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="outer-group">
    <div class="mb-3 text-center fw-light fs-3">Login to Hidden Inventory</div>
    <div class="login bg-body-secondary rounded border p-4 shadow-sm">
        <form method="POST" action="">
            {% csrf_token %}
            <div class="form-floating mb-3">
                <input type="text" class="form-control" id="loginUsername" name="username" placeholder>
                <label for="loginUsername">Username</label>
            </div>
            <div class="form-floating mb-3">
                <input type="password" class="form-control" id="loginPassword" name="password" placeholder>
                <label for="loginPassword">Password</label>
            </div>
            <div class="d-grid gap-2 mx-auto mt-2 mb-3">
                <button type="submit" class="login_btn btn btn-block btn-primary bg-gradient">Login</button>
            </div>
        </form>
    
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
            
        <div class="text-center text-body-secondary">Don't have an account yet? <a href="{% url 'main:register' %}" class="link-offset-2 link-underline link-underline-opacity-0">Register</a></div>
    </div>    
</div>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <style>
        .description {
            text-align: left;
            overflow: hidden;
        }
    </style>
{% endblock meta %}

{% block content %}
    <h1>
        Current Inventory
    </h1>
    <p class="bd-lead" id="items_amount">
        Registered items: {{ items|length }}
    </p>
    {% if items|length != 0  %}
    <div id="item_table" class="row row-cols-1 row-cols-lg-4 row-cols-md-2 row-cols-sm-1 g-4 mb-4 main-cards" style=".main-cards:last-child { color: red!important; }">        
        {% include 'placeholder_cards.html' %}
    </div>
    {% else %}
    <div class="mb-4">No items associated with this account!</div>
    {% endif %}

    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addModal">
        <span>
            <svg class="me-1 p-0" width="18" height="18" fill="none" viewBox="2 2 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12 2c5.523 0 10 4.477 10 10s-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2Zm0 1.5a8.5 8.5 0 1 0 0 17 8.5 8.5 0 0 0 0-17ZM12 7a.75.75 0 0 1 .75.75v3.5h3.5a.75.75 0 0 1 0 1.5h-3.5v3.5a.75.75 0 0 1-1.5 0v-3.5h-3.5a.75.75 0 0 1 0-1.5h3.5v-3.5A.75.75 0 0 1 12 7Z" fill="#fff"/></svg>
        </span>
        Add Item
    </button>

    <!-- MODAL -->
    {% include 'ajax_add_modal.html' %}
    {% include 'ajax_delete_modal.html' %}
    {% include 'ajax_edit_modal.html' %}
    
{% endblock content %}

{% block scripts %}
<script>
    const url_get_items = "{% url 'main:get_items_json' %}";
    const url_get_an_item = "{% url 'main:get_an_item' id=12345 %}";
    const url_increment_item = "{% url 'main:increment_item_ajax' id=12345 %}";
    const url_decrement_item = "{% url 'main:decrement_item_ajax' id=12345 %}";
    const url_create_item = "{% url 'main:create_item_ajax' %}"
    const url_delete_item = "{% url 'main:delete_item_ajax' id=12345 %}"
    const url_edit_item = "{% url 'main:edit_item_ajax' id=12345 %}";
</script>
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
{% endblock scripts %}

main/templates/placeholder_cards.html
{% for i in '012'|make_list %}
    <div class="col">
      <div class="card h-100" aria-hidden="true">
          <div class="card-body">
              <h5 class="card-title text-center placeholder-glow">
                <span class="placeholder col-6"></span>
              </h5>
              <hr/>
              <p class="card-text mb-3 placeholder-glow">
                <span class="placeholder col-12"></span>
                <span class="placeholder col-5"></span>
                <span class="placeholder col-6"></span>
              </p>
              <div class="container text-left">
                  <div class="row g-2 mb-1">
                      <div class="text-body-secondary col-4 p-0 placeholder-glow"><span class="placeholder col-10"></span></div>
                      <div class="col-8 p-0 placeholder-glow"><span class="placeholder col-5"></span></div>
                  </div>
                  <div class="row g-2 mb-1">
                      <div class="text-body-secondary col-4 p-0 placeholder-glow"><span class="placeholder col-8"></span></div>
                      <div class="col-8 p-0 placeholder-glow"><span class="placeholder col-4"></span></div>
                  </div>
                  <div class="row g-2 mb-1">
                    <div class="text-body-secondary col-4 p-0 placeholder-glow"><span class="placeholder col-4"></span></div>
                    <div class="col-8 p-0 placeholder-glow"><span class="placeholder col-6"></span></div>
                  </div>
                  <div class="row g-2 mb-1">
                    <div class="text-body-secondary col-4 p-0 placeholder-glow"><span class="placeholder col-10"></span></div>
                    <div class="col-8 p-0 placeholder-glow"><span class="placeholder col-10"></span></div>
                  </div>
              </div>
          </div>
          <div class="card-footer">
              <div class="gap-2 d-flex justify-content-end">
                  <div class="btn-group" role="group">
                      <button type="button" class="btn btn-secondary p-2 disabled placeholder col-1" aria-disabled="true"></button>
                      <button type="button" class="btn btn-secondary p-2 disabled placeholder col-1" aria-disabled="true"></button>
                  </div>
                  <button type="button" class="btn btn-warning disabled placeholder col-1" aria-disabled="true"></button>
                  <button type="button" class="btn btn-danger disabled placeholder col-1" aria-disabled="true"></button>
              </div>
          </div>
      </div>
    </div>
{% endfor %}

main/templates/register.html
{% extends 'base.html' %}

{% block content %}  
<div class="outer-group">
    <div class="mb-3 text-center fw-light fs-3 text">Register a new account</div>
    <div class = "login rounded bg-light-subtle border p-4 shadow-sm">
        <form method="POST">
            {% csrf_token %}  
            <table class="table table-borderless table-transparent">
                <tbody>
                    {{ form.as_table }}
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="2">
                            <div class="d-grid gap-2 col-6 mx-auto mt-2">
                            <button type="submit" class="login_btn btn btn-block btn-success bg-gradient">Daftar</button>
                            </div>
                        </td>
                    </tr> 
                </tfoot>
            </table>  
        </form>

        {% if messages %}  
            <ul>   
                {% for message in messages %}  
                    <li color="#e25028">{{ message }}</li>  
                    {% endfor %}  
            </ul>   
        {% endif %}

        <div class="text-center">Already have an account? <a href="{% url 'main:login' %}" class="link-offset-2 link-underline link-underline-opacity-0">Login</a></div>
    </div>  
</div>
{% endblock content %}